### ISSUE TITLE
Functionality missing for iOS

### ISSUE THREAD

**Issue by EnjoyBacon7** [ybizeul/ybFeed#2]
With releases mentioning iOS fixes, I don't understand how to paste content into a feed. Either touch isn't supported or I am missing something.

Steps to reproduce:

1. Create a feed
2. Try to paste text or an image on iOS
3. Contemplate the lack of pasting

Expected behavior:

Pasting

Current Behavior:

No Pasting

It seems the issue stems from the inexistence of a field to paste to.
![image](https://github.com/ybizeul/ybFeed/assets/59032058/79b17da8-279b-48e0-a139-a990143dd3f5)

**Comment by ybizeul** [comment]
Thank you for reporting this issue @EnjoyBacon7.

Here at ybFeed, we are taking customer feedback very seriously, and I can assure you this has been escalated to the top of our organization, our best people are working on it.

**Comment by ybizeul** [comment]
Good Sir,

The whole team worked tirelessly over the weekend to fix what, we clearly see now, was a serious shortcoming of ybFeed. We are very grateful that you were able to spot this issue before our product hits global markets.

We are eternally in your debt and we hope we will be collaborating again in the future.

Yours greatly

ybFeed Developer Team.
